package pl.commercelink.inventory.supplier.api.support;

import javax.net.ssl.HttpsURLConnection;
import javax.net.ssl.SSLContext;
import javax.net.ssl.TrustManager;
import javax.net.ssl.X509TrustManager;
import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.X509Certificate;
import java.util.Base64;

/*
    Fully generated by ChatGPT
*/
public class HttpFileDownloader {

    public byte[] downloadResource(String inputFile) throws ResourceDownloadException {
        return downloadResource(inputFile, null, null);
    }

    public byte[] downloadResource(String inputFile, String username, String password) throws ResourceDownloadException {
        try {
            HttpURLConnection connection = openConnectionWithRedirects(inputFile, username, password);
            try (BufferedInputStream in = new BufferedInputStream(connection.getInputStream());
                 ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream()) {
                byte[] dataBuffer = new byte[1024];
                int bytesRead;
                while ((bytesRead = in.read(dataBuffer, 0, 1024)) != -1) {
                    byteArrayOutputStream.write(dataBuffer, 0, bytesRead);
                }
                return byteArrayOutputStream.toByteArray();
            }
        } catch (IOException | NoSuchAlgorithmException | KeyManagementException e) {
            throw new ResourceDownloadException("Failed to download resources", e);
        }
    }

    private HttpURLConnection openConnectionWithRedirects(String fileUrl, String username, String password) throws IOException, NoSuchAlgorithmException, KeyManagementException {
        URL url = new URL(fileUrl);
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        if (connection instanceof HttpsURLConnection) {
            SSLContext sslContext = SSLContext.getInstance("TLS");
            TrustManager[] trustManagers = {new X509TrustManager() {
                public X509Certificate[] getAcceptedIssuers() {
                    return null;
                }

                public void checkClientTrusted(X509Certificate[] certs, String authType) {
                }

                public void checkServerTrusted(X509Certificate[] certs, String authType) {
                }
            }};
            sslContext.init(null, trustManagers, new java.security.SecureRandom());
            ((HttpsURLConnection) connection).setSSLSocketFactory(sslContext.getSocketFactory());
        }
        connection.setInstanceFollowRedirects(false);
        connection.setRequestMethod("GET");

        if (username != null && password != null) {
            String auth = username + ":" + password;
            byte[] encodedAuth = Base64.getEncoder().encode(auth.getBytes(StandardCharsets.UTF_8));
            String authHeaderValue = "Basic " + new String(encodedAuth);
            connection.setRequestProperty("Authorization", authHeaderValue);
        }

        int responseCode = connection.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_MOVED_TEMP
                || responseCode == HttpURLConnection.HTTP_MOVED_PERM
                || responseCode == HttpURLConnection.HTTP_SEE_OTHER
                || responseCode == 307
                || responseCode == 308) {
            String newUrl = connection.getHeaderField("Location");
            if (newUrl != null) {
                return openConnectionWithRedirects(newUrl, username, password);
            } else {
                throw new IOException("Failed to get redirect URL.");
            }
        }
        return connection;
    }
}